services:
    server:
       build: ./server
       restart: always
       volumes:
        - ./server:/app/
       command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
       ports:
        - 8000:8000
       environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-^qg*s3_2v33yc@u&m*q7u4mc=l#4rzrbmw-n0-4v5f49=5_&^=
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
       depends_on:
        - db
        - redis
    redis:
        image: redis/redis-stack
        ports:
         - 8001:8001
    db:
        image: postgres:13.0-alpine
        volumes:
         - .postgres_data:/var/lib/postgresql/data/
        ports: 
         - 5432:5432
        restart: always
        environment:
         - POSTGRES_DB=valute
         - POSTGRES_USER=valute
         - POSTGRES_PASSWORD=valute
    celery:
        build: ./server
        command: celery -A send_email worker -l info
        environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-^qg*s3_2v33yc@u&m*q7u4mc=l#4rzrbmw-n0-4v5f49=5_&^=
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        volumes:
        - ./server:/app/
        depends_on:
        - redis

    celery-beat:
        build: ./server
        command: celery -A send_email beat -l info
        volumes:
        - ./server:/app/
        environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-^qg*s3_2v33yc@u&m*q7u4mc=l#4rzrbmw-n0-4v5f49=5_&^=
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
        - redis

    dashboard:
        build: ./server
        command: celery flower -A send_email --port=5555 --broker=redis://redis:6379/0
        environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-^qg*s3_2v33yc@u&m*q7u4mc=l#4rzrbmw-n0-4v5f49=5_&^=
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        ports:
            - 5555:5555
        depends_on:
            - server
            - redis
            - celery