# Generated by Django 4.1.7 on 2023-02-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('num_code', models.IntegerField()),
                ('char_code', models.CharField(max_length=3)),
                ('nominal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('valute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.valute')),
            ],
        ),
    ]
