# Generated by Django 4.1.7 on 2023-03-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='value',
            field=models.FloatField(default=1, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valute',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название валюты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='valute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.valute', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='valute',
            name='char_code',
            field=models.CharField(max_length=3, verbose_name='буквенный код'),
        ),
        migrations.AlterField(
            model_name='valute',
            name='nominal',
            field=models.IntegerField(verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='valute',
            name='num_code',
            field=models.IntegerField(verbose_name='числовой код'),
        ),
        migrations.AlterField(
            model_name='valute',
            name='unique_id',
            field=models.CharField(max_length=20, verbose_name='обозначение'),
        ),
    ]
