# Generated by Django 4.1.7 on 2023-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0002_curs_value_valute_name_alter_curs_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='datetime',
            field=models.DateTimeField(verbose_name='дата'),
        ),
    ]
